In [1]:
# 1.导入包
import numpy as np

In [2]:
# 2.打印numpy的版本和配置说明 
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/lxh/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/lxh/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/lxh/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/lxh/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/lxh/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/lxh/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/lxh/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/lxh/opt/anaconda3/include']


In [3]:
# 3.创建一个长度为10的空向量
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 4. 如何找到任何一个数组的内存大小？
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [6]:
# 5. 如何从命令行得到numpy中add函数的说明文档?
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [7]:
# 6. 创建一个长度为10并且除了第五个值为1的空向量
Z = np.zeros(10)
Z[4] = 1
print(Z)



[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
# 7. 创建一个值域范围从10到49的向量
Z = np.arange(10,50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
# 8. 反转一个向量(第一个元素变为最后一个)
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [11]:
# 9. 创建一个 3x3 并且值从0到8的矩阵
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
# 10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [ ]:
# 10.1 pandas找到非零元素对应index、column、以及值

import time
import pandas as pd
import numpy as np

# data 
tmp = pd.DataFrame(data=np.zeros((1000,1000)))
tmp.iloc[998,998] = 1

# pd 数据量大很慢
def test_df(va2):
    t1 = time.time()
    res2 = []
    for idx,val in va2.iterrows():
        for col in va2.columns:
            if val[col] > 0:
                res2.append((idx,col,val[col]))
    print(time.time()-t1)
    return res2
test_df(tmp)

# np 速度快
def test_np(df):
    t1 = time.time()
    npd = np.array(df)
    nonzero_index = np.nonzero(npd) # 以二维数组为例，返回非零元素行标、列标
    nonzero_data = npd[nonzero_index] # 非零数值列表
    nonzero_df_index = df.index[nonzero_index[0]] # 非零索引
    nonzero_df_columns = df.columns[nonzero_index[1]] # 非零字段列名
    res = list(zip(nonzero_df_index,nonzero_df_columns,nonzero_data))
    print(time.time()-t1)
    return res
test_np(tmp)

# 耗时对比：8.707995176315308/0.014760494232177734 = 589
# 大约提速600倍



In [14]:
# 11. 创建一个 3x3 的单位矩阵
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# 12. 创建一个 3x3x3的随机数组
Z = np.random.random((3,3,3))
print(Z)

[[[0.58234322 0.55154633 0.22445061]
  [0.25164608 0.6838092  0.0152047 ]
  [0.45404905 0.25210313 0.29676001]]

 [[0.70450458 0.01082732 0.6017346 ]
  [0.33904527 0.98248598 0.21969467]
  [0.15080626 0.15479699 0.00611837]]

 [[0.23810024 0.46953085 0.9169118 ]
  [0.5892025  0.67538298 0.70011266]
  [0.19499532 0.72061221 0.70911775]]]


In [31]:
# 13. 创建一个 10x10 的随机数组并找到它的最大值和最小值, 及其对应下标
Z = np.random.random((5,5))
print(Z)
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)
print(Z.argmin(), Z.argmax())

[[0.27526417 0.37298363 0.94301064 0.73371958 0.88606032]
 [0.40973739 0.07874766 0.65135743 0.54298395 0.34998658]
 [0.21078713 0.63744741 0.47211027 0.75820463 0.22915628]
 [0.21134601 0.05018442 0.37972641 0.39403745 0.9070864 ]
 [0.08253669 0.55346816 0.75074881 0.57023017 0.57494053]]
0.05018441866747381 0.9430106377283017
16 2


In [34]:
# 14. 创建一个长度为30的随机向量并找到它的平均值
Z = np.random.random(30)
print(Z)
Z.mean()

[0.18961171 0.93252075 0.84255658 0.46352521 0.2389275  0.99825274
 0.00505293 0.81747098 0.53021065 0.15460361 0.96668275 0.1139799
 0.23821822 0.55677071 0.01687055 0.17002071 0.86970868 0.27063197
 0.67380525 0.26427913 0.82362376 0.81351969 0.12353466 0.44884795
 0.78985126 0.84480649 0.90756354 0.49790984 0.0640976  0.0081592 ]


0.4878538176191794

In [35]:
# 15. 创建一个二维数组，其中边界值为1，其余值为0
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [36]:
# 16. 对于一个存在在数组，如何添加一个用0填充的边界?
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [41]:
# 17. 以下表达式运行的结果分别是什么?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [42]:
# 18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [43]:
# 19. 创建一个8x8 的矩阵，并且设置成棋盘样式
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# 